const quotes = [
    "Seus olhos são hipnotizantes.",
    "Sua pele é suave quanto uma brisa de manhã.",
    "Você será para mim única. O essencial é invisível aos olhos.",
    "Seu sorriso ilumina meu dia.",
    "Cada traço do seu rosto é perfeito.",
    "Sua presença torna o mundo mais bonito.",
    "Seu olhar é como um convite para o paraíso.",
    "Sua inteligência é inspiradora.",
    "Você é a pessoa mais determinada que já conheci.",
    "Você é especial.",
    "Você existir é como um abraço acolhedor.",
    "Invejo como consegue ser tão gentil.",
    "Seu cheiro é viciante.",
    "Sua compreensão profunda torna cada conversa significativa.",
    "Sua voz é doce como música.",
    "Sua risada me aquece.",
    "Seu toque me enfraquece.",
    "Sua energia é contagiante.",
    "Todo segundo de tempo passado com você é precioso.",
    "Nunca me canso de você.",
    "É impossível não gostar de você.",
    "Amo você.",
    "Você é arte.",
    "I swear I changed my ways for the better 'cause I wanna be with you forever",
    "https://open.spotify.com/embed/track/3dhjNA0jGA8vHBQ1VdD6vV?utm_source=generator",
    "https://open.spotify.com/embed/track/3w3y8KPTfNeOKPiqUTakBh?utm_source=generator",
    "https://open.spotify.com/embed/track/0GNI8K3VATWBABQFAzBAYe?utm_source=generator",
    "https://open.spotify.com/embed/track/2psRActEWsTlYYd7EDoyVR?utm_source=generator",
    "https://open.spotify.com/embed/track/7DKS0rX27cCEPsK0R6tFWS?utm_source=generator",
    "https://open.spotify.com/embed/track/1WbhIxkn5ECsOwUm795iX1?utm_source=generator",
    "https://open.spotify.com/embed/track/5LrN7yUQAzvthd4QujgPFr?utm_source=generator",
    "https://www.youtube.com/embed/VJ3Ynf5lysM?si=PAVNOLSkhuoGtpU1",
    "Sua ausência me desespera.",
    "Você é meu sonho.",
    "I can't seem to not need to need you",
    "I would love just to be stuck to your side, not with anybody else, anybody else",
    "Hoje vi as estrelas, me perdi um pouco, mas senti como se te encontrasse.",
    "Você me veio de súbito, \nComo uma chuva que não avisa. \nNem as formigas poderiam prever \nE elas se afogariam... \nComo eu me afoguei.",
    {image: "src/elisa.jpg"},
    {image: "src/us.jpg"},
];
